DROP TABLE IF EXISTS maps CASCADE;

CREATE TABLE maps (
id SERIAL PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
is_active BOOLEAN NOT NULL DEFAULT TRUE,
center_long FLOAT(6) NOT NULL,
center_lat FLOAT(6) NOT NULL,
zoom SMALLINT NOT NULL DEFAULT 13,
type VARCHAR(20) NOT NULL DEFAULT 'roadmap',
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
